Controllers/AlimentoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.Models.Utilies;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    public class AlimentoController : Controller
    {

        private readonly IApiService _apiService;

        public AlimentoController(IApiService apiService)
        {
            _apiService = apiService;
        }   


        // GET: ProductoController  
        public async Task<IActionResult> Index()
        {
            try
            {
                List<Alimento> productos = await _apiService.obtenerProductos();
                return View(productos);
            } catch (Exception e)
            {
                return View(new List<Alimento>());
            }
        }

        // GET: ProductoController/Details/5
        public async Task<ActionResult> Details(int IdProducto)
        {
            var producto = await _apiService.obtenerProducto(IdProducto);
            if (producto != null)
            {
                return View(producto);
            }
            return RedirectToAction("Index");
        }

        // GET: ProductoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductoController/Create
        [HttpPost]
        public async Task<IActionResult> Create(Alimento producto)
        {
            var pCreado = await _apiService.añadirProducto(producto);
            if (pCreado)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: ProductoController/Edit/5
        public async Task<IActionResult> Edit(int IdProducto)
        {
            var pEditar = await _apiService.obtenerProducto(IdProducto);
            if (pEditar != null)
            {
                return View(pEditar);
            }
            return RedirectToAction("Index");
        }

        // POST: ProductoController/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(Alimento producto)
        {
            var pAEditar = await _apiService.actualizarProducto(producto.IdProducto, producto);
            if (pAEditar != null)
            {
                return RedirectToAction(nameof(Index));
            }   
            return View(pAEditar);  
        }


        // GET: ProductoController/Delete/5
        public ActionResult Delete(int IdProducto)
        {
            var producto = _apiService.eliminarProducto(IdProducto);
            return RedirectToAction(nameof(Index));

        }

    }
}

Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.Models.Utilies;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    public class EmpleadoController : Controller
    {
        private readonly IApiService _apiService;

        public EmpleadoController(IApiService apiService)
        {
            _apiService = apiService;
        }


        // GET: ProductoController  
        public async Task<IActionResult> Index1()
        {
            try
            {
                List<Empleados> empleado = await _apiService.obtenerEmpleado();
                return View(empleado);
            }
            catch (Exception e)
            {
                return View(new List<Empleados>());
            }
        }

        // GET: ProductoController/Details/5
        public async Task<ActionResult> Details(string cedula)
        {
            var empleado = await _apiService.obtenerEmpleado(cedula);
            if (empleado != null)
            {
                return View(empleado);
            }
            return RedirectToAction("Index1");
        }

        // GET: ProductoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductoController/Create
        [HttpPost]
        public async Task<IActionResult> Create(Empleados empleado)
        {
            var pCreado = await _apiService.añadirEmpleado(empleado);
            if (pCreado)
            {
                return RedirectToAction(nameof(Index1));
            }
            return View(empleado);
        }

        // GET: ProductoController/Edit/5
        public async Task<IActionResult> Edit(string cedula)
        {
            var pEditar = await _apiService.obtenerEmpleado(cedula);
            if (pEditar != null)
            {
                return View(pEditar);
            }
            return RedirectToAction("Index1");
        }

        // POST: ProductoController/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(Empleados empleado)
        {
            var pAEditar = await _apiService.actualizarEmpleado(empleado.Cedula, empleado);
            if (pAEditar != null)
            {
                return RedirectToAction(nameof(Index1));
            }
            return View(pAEditar);
        }


        // GET: ProductoController/Delete/5
        public ActionResult Delete(string cedula)
        {
            var producto = _apiService.eliminarEmpleado(cedula);
            return RedirectToAction(nameof(Index1));

        }

    }
}

Controllers/PlatoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.Models.Utilies;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    public class PlatoController : Controller
    {

        private readonly IApiService _apiService;

        public PlatoController(IApiService apiService)
        {
            _apiService = apiService;
        }


        // GET: ProductoController  
        public async Task<IActionResult> Index2()
        {
            try
            {
                List<Platos> productos = await _apiService.obtenerPlato();
                return View(productos);
            }
            catch (Exception e)
            {
                return View(new List<Platos>());
            }
        }

        // GET: ProductoController/Details/5
        public async Task<ActionResult> Details(int IdPlato)
        {
            var producto = await _apiService.obtenerPlato(IdPlato);
            if (producto != null)
            {
                return View(producto);
            }
            return RedirectToAction("Index2");
        }

        // GET: ProductoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductoController/Create
        [HttpPost]
        public async Task<IActionResult> Create(Platos plato)
        {
            var pCreado = await _apiService.añadirPlato(plato);
            if (pCreado)
            {
                return RedirectToAction(nameof(Index2));
            }
            return View(plato);
        }

        // GET: ProductoController/Edit/5
        public async Task<IActionResult> Edit(int IdPlato)
        {
            var pEditar = await _apiService.obtenerPlato(IdPlato);
            if (pEditar != null)
            {
                return View(pEditar);
            }
            return RedirectToAction("Index2");
        }

        // POST: ProductoController/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(Platos plato)
        {
            var pAEditar = await _apiService.actualizarPlato(plato.IdPlato, plato);
            if (pAEditar != null)
            {
                return RedirectToAction(nameof(Index2));
            }
            return View(pAEditar);
        }


        // GET: ProductoController/Delete/5
        public ActionResult Delete(int IdPlato)
        {
            var producto = _apiService.eliminarPlato(IdPlato);
            return RedirectToAction(nameof(Index2));

        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TIENDA DE COMIDA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/materia.min.css" />
    <!-- <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrapCyborg.min.css" /> -->
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
               
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CAFE PARRILLA WEB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="bi bi-house-fill"></i> Inicio
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Alimento" asp-action="Index">
                                <i class="bi bi-basket2-fill"></i> Ingredientes
                            </a>
                        </li>
                        <li class="nav-item">
                            <!-- Agrega el ícono de persona al lado izquierdo del enlace "Empleados" -->
                            <a class="nav-link" asp-area="" asp-controller="Empleado" asp-action="Index1">
                                <i class="bi bi-file-person-fill"></i> Empleados
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Plato" asp-action="Index2">
                                <i class="bi bi-brightness-alt-high-fill"></i> Productos
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-gray">
       
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>